[package]
name = "micro-shell"
version = "0.1.0"
authors = ["33665"]
edition = "2018"
regex = "1.3.7"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"